In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #
#                                              실전 데이터 분석 코드 (교재 초보자 용)                                                    #
#                                                                                                                                     #
#                                                                                                             "Handmade by JHL"       #
#######################################################################################################################################

In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #                                    
#                                                     판다스 - 데이터 핸들링 기초                                                       #
#                                                                                                                                     #
#                                                                                                                                     #
#######################################################################################################################################

In [ ]:
# 필요 라이브러리 불러오기
import pandas as pd
import numpy as np

In [2]:
# 데이터 불러오기 및 데이터 규모 파악
df = pd.read_csv('BookExample.csv')
print("Data Shape:", df.shape)

# 데이터 앞 5개 확인
df.head()

Data Shape: (20000, 33)


ID  target        v1        v2 v3        v4         v5        v6        v7  \
0   3       1  1.335739  8.727474  C  3.921026   7.915266  2.599278  3.176895   
1   4       1  0.000000  0.000000  C  0.000000   9.191265  0.000000  0.000000   
2   5       1  0.943877  5.310079  C  4.410969   5.326159  3.979592  3.928571   
3   6       1  0.797415  8.304757  C  4.225930  11.627438  2.097700  1.987549   
4   8       1  0.000000  0.000000  C  0.000000   0.000000  0.000000  0.000000   

         v8  ...   v22           v23  v24       v25       v26       v27  \
0  0.012941  ...   XDX -1.720000e-08    C  0.139412  1.720818  3.393503   
1  2.301630  ...   GUV  0.000000e+00    C  3.056144  0.000000  0.000000   
2  0.019645  ...    FQ -2.790000e-07    E  0.113997  2.244897  5.306122   
3  0.171947  ...  ACUE -4.810000e-07    D  0.148843  1.308269  2.303640   
4  0.000000  ...   HIT  0.000000e+00    E  0.000000  0.000000  0.000000   

        v28       v29  v30  v31  
0  0.590122  8.880867    C    A  
1  0.000000  0.000000    C    A  
2  0.836005  7.499999    0    A  
3  8.926662  8.874521    C    B  
4  0.000000  0.000000    0    A  

[5 rows x 33 columns]

In [25]:
# 데이터 마지막 5개 확인
df.tail()

ID  target        v1        v2 v3        v4         v5        v6  \
19995  40048       1  0.000000  0.000000  C  0.000000   0.000000  0.000000   
19996  40051       1  2.019311  3.284808  C  1.954289   8.942205  2.535684   
19997  40052       0  0.913579  8.132525  C  3.555315  12.461332  2.580248   
19998  40055       1  0.000000  0.000000  C  0.000000   0.000000  0.000000   
19999  40056       0  0.487483  7.638427  C  4.044045   8.511991  1.299956   

             v7        v8  ...   v22           v23  v24       v25       v26  \
19995  0.000000  0.000000  ...  ACCB  0.000000e+00    D  0.000000  0.000000   
19996  1.931150  1.119962  ...   KDA  1.300000e-08    C  1.728577  1.754828   
19997  2.067901  0.137280  ...  AAES -7.420000e-07    E  0.153086  1.697531   
19998  0.000000  0.000000  ...   OST  0.000000e+00    E  0.000000  0.000000   
19999  2.362758  0.773913  ...   QYP  7.393090e-01    E  1.159701  1.191626   

            v27       v28       v29  v30  v31  
19995  0.000000  0.000000  0.000000    0    B  
19996  1.712845  5.090871  8.404702    0    B  
19997  1.802468  6.925380  9.685186    G    A  
19998  0.000000  0.000000  0.000000    C    A  
19999  4.918753  4.866367  5.085640    0    A  

[5 rows x 33 columns]

In [3]:
# 데이터 정보 파악 1
df.describe()

ID        target            v1            v2            v4  \
count  20000.000000  20000.000000  20000.000000  20000.000000  20000.000000   
mean   20015.657050      0.757850      0.926345      4.239573      2.352223   
std    11589.317914      0.428395      1.142191      4.316143      2.226008   
min        3.000000      0.000000     -0.000001      0.000000      0.000000   
25%     9973.750000      1.000000      0.000000      0.000000      0.000000   
50%    19933.500000      1.000000      0.547472      4.127830      2.774881   
75%    30099.500000      1.000000      1.621064      7.526088      4.333625   
max    40056.000000      1.000000     12.758620     18.770830     11.831778   

                 v5            v6            v7            v8            v9  \
count  20000.000000  2.000000e+04  2.000000e+04  2.000000e+04  2.000000e+04   
mean       5.044359  1.380275e+00  1.410862e+00  8.780690e-01  5.125201e+00   
std        4.572065  1.283248e+00  1.305883e+00  2.222752e+00  4.697482e+00   
min        0.000000 -6.110000e-07 -9.470000e-07 -7.780000e-07 -9.830000e-07   
25%        0.000000  0.000000e+00  0.000000e+00  0.000000e+00  0.000000e+00   
50%        6.753678  1.784925e+00  1.841375e+00  3.755553e-02  6.858174e+00   
75%        8.922577  2.479908e+00  2.526421e+00  5.884071e-01  9.286154e+00   
max       20.000000  7.272728e+00  8.888889e+00  2.000000e+01  2.000000e+01   

       ...           v18           v19           v20           v21  \
count  ...  20000.000000  20000.000000  20000.000000  20000.000000   
mean   ...      0.480450      0.126200     10.093129      7.002664   
std    ...      0.631497      0.135162      8.839707      1.158836   
min    ...      0.000000      0.000000      0.000000      0.000000   
25%    ...      0.000000      0.000000      0.000000      6.409858   
50%    ...      0.251961      0.159731     16.530204      7.044975   
75%    ...      0.835394      0.206592     18.151973      7.666763   
max    ...     20.000000      3.157777     20.000001     15.767890   

                v23           v25           v26           v27           v28  \
count  2.000000e+04  20000.000000  2.000000e+04  2.000000e+04  20000.000000   
mean   6.475178e-01      0.997521  1.065201e+00  1.558645e+00      2.905602   
std    3.139116e+00      2.393770  1.016667e+00  1.497022e+00      3.250382   
min   -1.000000e-06      0.000000 -7.550000e-07 -7.200000e-07      0.000000   
25%    0.000000e+00      0.000000  0.000000e+00  0.000000e+00      0.000000   
50%    0.000000e+00      0.122284  1.294503e+00  1.836450e+00      1.607868   
75%    3.170000e-07      0.764558  1.901728e+00  2.782713e+00      5.375775   
max    2.000000e+01     20.000001  9.166666e+00  1.111111e+01     19.848194   

                v29  
count  2.000000e+04  
mean   4.657864e+00  
std    4.173179e+00  
min   -3.040000e-07  
25%    0.000000e+00  
50%    6.686271e+00  
75%    8.485299e+00  
max    1.400000e+01  

[8 rows x 28 columns]

In [4]:
# 데이터 정보 파악 2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 33 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ID      20000 non-null  int64  
 1   target  20000 non-null  int64  
 2   v1      20000 non-null  float64
 3   v2      20000 non-null  float64
 4   v3      20000 non-null  object 
 5   v4      20000 non-null  float64
 6   v5      20000 non-null  float64
 7   v6      20000 non-null  float64
 8   v7      20000 non-null  float64
 9   v8      20000 non-null  float64
 10  v9      20000 non-null  float64
 11  v10     20000 non-null  float64
 12  v11     20000 non-null  float64
 13  v12     20000 non-null  float64
 14  v13     20000 non-null  float64
 15  v14     20000 non-null  float64
 16  v15     20000 non-null  float64
 17  v16     20000 non-null  float64
 18  v17     20000 non-null  float64
 19  v18     20000 non-null  float64
 20  v19     20000 non-null  float64
 21  v20     20000 non-null  float64
 22

In [5]:
# 결측치 파악
df.isnull().sum()

ID        0
target    0
v1        0
v2        0
v3        0
v4        0
v5        0
v6        0
v7        0
v8        0
v9        0
v10       0
v11       0
v12       0
v13       0
v14       0
v15       0
v16       0
v17       0
v18       0
v19       0
v20       0
v21       0
v22       0
v23       0
v24       0
v25       0
v26       0
v27       0
v28       0
v29       0
v30       0
v31       0
dtype: int64

In [8]:
# unique/nunique 한 값 확인
print("unique:", df["target"].unique())
print("nunque:", df["target"].nunique())

unique: [1 0]
nunque: 2


In [9]:
# 범주형 데이터 빈도수 파악
df["target"].value_counts()

1    15157
0     4843
Name: target, dtype: int64

In [12]:
# target컬럼 데이터만 추출
df[["target"]].head()

target
0       1
1       1
2       1
3       1
4       1

In [46]:
# ID 및 target 컬럼 데이터만 추출
df[["target", "v1"]].head()

target        v1
0       1  1.335739
1       1  0.000000
2       1  0.943877
3       1  0.797415
4       1  0.000000

In [18]:
# 특정 컬럼 통계치 확인
df["v1"].describe()

count    20000.000000
mean         0.926345
std          1.142191
min         -0.000001
25%          0.000000
50%          0.547472
75%          1.621064
max         12.758620
Name: v1, dtype: float64

In [24]:
# 특정 타입의 데이터만 추출
# ("object, int32, int64, float32, float64" - 중 선택 가능)
df.select_dtypes("object")

v3   v22 v24 v30 v31
0      C   XDX   C   C   A
1      C   GUV   C   C   A
2      C    FQ   E   0   A
3      C  ACUE   D   C   B
4      C   HIT   E   0   A
...   ..   ...  ..  ..  ..
19995  C  ACCB   D   0   B
19996  C   KDA   C   0   B
19997  C  AAES   E   G   A
19998  C   OST   E   C   A
19999  C   QYP   E   0   A

[20000 rows x 5 columns]

In [45]:
### 수치형 데이터 인덱싱 - 기본

# index 위치로 조회
df.loc[:5]

# column 위치로 조회
df.loc[:5,"v1"]

# target에서 0을 만족하는 데이터만 추출
df[ df.loc[:, "target"] == 0 ]

# target 이 0을 갖고, v3가 C를 갖는 데이터만 추출
df[ (df["target"] == 0) & (df["v3"] == "C") ]

ID  target        v1         v2 v3        v4         v5        v6  \
5          9       0  0.000000   0.000000  C  0.000000   8.856791  0.000000   
6         12       0  0.899806   7.312995  C  3.494148   9.946200  1.926070   
12        28       0  0.000000   0.000000  C  0.000000   0.000000  0.000000   
29        55       0  2.415670  14.960392  C  4.356980   8.520510  2.132753   
35        67       0  2.843810   7.961986  C  4.372291   8.381346  2.305791   
...      ...     ...       ...        ... ..       ...        ...       ...   
19976  40017       0  2.273220   7.747975  C  4.253893   8.193344  2.428624   
19986  40035       0  0.000000   0.000000  C  0.000000   0.000000  0.000000   
19992  40045       0  0.000000   0.000000  C  0.000000   7.855438  0.000000   
19997  40052       0  0.913579   8.132525  C  3.555315  12.461332  2.580248   
19999  40056       0  0.487483   7.638427  C  4.044045   8.511991  1.299956   

             v7        v8  ...   v22           v23  v24       v25       v26  \
5      0.000000  0.359993  ...   AYX  0.000000e+00    A  0.218458  0.000000   
6      1.770427  0.066251  ...   NFD  7.810000e-07    E  0.180765  1.070040   
12     0.000000  0.000000  ...   QKP  0.000000e+00    E  0.000000  0.000000   
29     2.023938  0.035822  ...   FLR  2.230000e-08    E  0.130472  1.595937   
35     2.876751  1.231511  ...  ACOZ -7.950000e-07    E  0.910234  1.882148   
...         ...       ...  ...   ...           ...  ...       ...       ...   
19976  2.399712  1.703670  ...   GLW  3.450000e-07    C  1.910470  2.478015   
19986  0.000000  0.000000  ...   YDU  0.000000e+00    E  0.000000  0.000000   
19992  0.000000  0.805805  ...   EYN  0.000000e+00    C  0.713341  0.000000   
19997  2.067901  0.137280  ...  AAES -7.420000e-07    E  0.153086  1.697531   
19999  2.362758  0.773913  ...   QYP  7.393090e-01    E  1.159701  1.191626   

            v27       v28       v29  v30  v31  
5      0.000000  0.000000  0.000000    0    A  
6      1.566147  4.393842  7.928015    G    A  
12     0.000000  0.000000  0.000000    0    A  
29     2.459195  1.962796  9.096844    0    A  
35     4.106507  7.787043  6.939336    0    A  
...         ...       ...       ...  ...  ...  
19976  2.161185  5.914047  8.586918    C    A  
19986  0.000000  0.000000  0.000000    0    A  
19992  0.000000  0.000000  0.000000    C    A  
19997  1.802468  6.925380  9.685186    G    A  
19999  4.918753  4.866367  5.085640    0    A  

[4714 rows x 33 columns]

In [47]:
# 컬럼명 변경
df.rename(columns={"ID": "ID_num" }, inplace=True)
df.head()

ID_num  target        v1        v2 v3        v4         v5        v6  \
0       3       1  1.335739  8.727474  C  3.921026   7.915266  2.599278   
1       4       1  0.000000  0.000000  C  0.000000   9.191265  0.000000   
2       5       1  0.943877  5.310079  C  4.410969   5.326159  3.979592   
3       6       1  0.797415  8.304757  C  4.225930  11.627438  2.097700   
4       8       1  0.000000  0.000000  C  0.000000   0.000000  0.000000   

         v7        v8  ...   v22           v23  v24       v25       v26  \
0  3.176895  0.012941  ...   XDX -1.720000e-08    C  0.139412  1.720818   
1  0.000000  2.301630  ...   GUV  0.000000e+00    C  3.056144  0.000000   
2  3.928571  0.019645  ...    FQ -2.790000e-07    E  0.113997  2.244897   
3  1.987549  0.171947  ...  ACUE -4.810000e-07    D  0.148843  1.308269   
4  0.000000  0.000000  ...   HIT  0.000000e+00    E  0.000000  0.000000   

        v27       v28       v29  v30  v31  
0  3.393503  0.590122  8.880867    C    A  
1  0.000000  0.000000  0.000000    C    A  
2  5.306122  0.836005  7.499999    0    A  
3  2.303640  8.926662  8.874521    C    B  
4  0.000000  0.000000  0.000000    0    A  

[5 rows x 33 columns]

In [71]:
# 새로운 컬럼 추가
df["new_col"] = 0
df.head()

ID_num  target        v1        v2 v3        v4         v5        v6  \
0       3       1  1.335739  8.727474  C  3.921026   7.915266  2.599278   
1       4       1  0.000000  0.000000  C  0.000000   9.191265  0.000000   
2       5       1  0.943877  5.310079  C  4.410969   5.326159  3.979592   
3       6       1  0.797415  8.304757  C  4.225930  11.627438  2.097700   
4       8       1  0.000000  0.000000  C  0.000000   0.000000  0.000000   

         v7        v8  ...           v23  v24       v25       v26       v27  \
0  3.176895  0.012941  ... -1.720000e-08    C  0.139412  1.720818  3.393503   
1  0.000000  2.301630  ...  0.000000e+00    C  3.056144  0.000000  0.000000   
2  3.928571  0.019645  ... -2.790000e-07    E  0.113997  2.244897  5.306122   
3  1.987549  0.171947  ... -4.810000e-07    D  0.148843  1.308269  2.303640   
4  0.000000  0.000000  ...  0.000000e+00    E  0.000000  0.000000  0.000000   

        v28       v29  v30  v31  new_col  
0  0.590122  8.880867    C    A        0  
1  0.000000  0.000000    C    A        0  
2  0.836005  7.499999    0    A        0  
3  8.926662  8.874521    C    B        0  
4  0.000000  0.000000    0    A        0  

[5 rows x 34 columns]

In [72]:
# 컬럼 삭제
df.drop("new_col", axis=1, inplace=True)
df.head()

ID_num  target        v1        v2 v3        v4         v5        v6  \
0       3       1  1.335739  8.727474  C  3.921026   7.915266  2.599278   
1       4       1  0.000000  0.000000  C  0.000000   9.191265  0.000000   
2       5       1  0.943877  5.310079  C  4.410969   5.326159  3.979592   
3       6       1  0.797415  8.304757  C  4.225930  11.627438  2.097700   
4       8       1  0.000000  0.000000  C  0.000000   0.000000  0.000000   

         v7        v8  ...   v22           v23  v24       v25       v26  \
0  3.176895  0.012941  ...   XDX -1.720000e-08    C  0.139412  1.720818   
1  0.000000  2.301630  ...   GUV  0.000000e+00    C  3.056144  0.000000   
2  3.928571  0.019645  ...    FQ -2.790000e-07    E  0.113997  2.244897   
3  1.987549  0.171947  ...  ACUE -4.810000e-07    D  0.148843  1.308269   
4  0.000000  0.000000  ...   HIT  0.000000e+00    E  0.000000  0.000000   

        v27       v28       v29  v30  v31  
0  3.393503  0.590122  8.880867    C    A  
1  0.000000  0.000000  0.000000    C    A  
2  5.306122  0.836005  7.499999    0    A  
3  2.303640  8.926662  8.874521    C    B  
4  0.000000  0.000000  0.000000    0    A  

[5 rows x 33 columns]

In [70]:
# 컬럼에 들어있는 특정 데이터 replace
# "0" --> "D" 변경
df.loc[df["v3"] =="0", "v3"]  = "D"
df["v3"].value_counts()

C    19377
D      594
A       24
B        5
Name: v3, dtype: int64

In [ ]:
# 작업 완료된 데이터프레임 컴퓨터에 파일(csv) 형태로 저장
df.to_csv("원하는 파일명을 쓰시오.csv")

In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #                                    
#                                                       넘파이 - 데이터 연산 기초                                                       #
#                                                                                                                                     #
#                                                                                                                                     #
#######################################################################################################################################

In [3]:
# 필요 라이브러리 불러오기
import pandas as pd
import numpy as np

In [ ]:
'''

넘파이(Numpy)는 Python에서 벡터, 행렬(matrix) 등 수치 연산을 수행하는 라이브러리입니다.           
내부적으로 C언어로 구현되어 있어 빠른 연산 속도를 자랑합니다.

넘파이에서는 모든 배열의 값이 기본적으로 같은 타입이어야 합니다.
그리고 넘파이에서는 각 차원(Dimension)을 축(axis)라고 표현합니다.

3D Space의 포인트를 [1,2,1] 과 같은 배열(array)로 표현가능 한데, 1개의 축을 가진다고 표현합니다.
(여기서 축은 3개의 요소(Element)를 가지고 있다고 하며 길이(Length)도 3입니다.)

넘파이에서 배열은 ndarray 또는 array라고도 부릅니다. 



Vector are implemented as dynamic arrays with list interface 
whereas arrays can be implemented as statically or dynamically with primitive data type interface. 
Size of arrays are fixed whereas the vectors are resizable 
i.e they can grow and shrink as vectors are allocated on heap memory.

'''

In [ ]:
##################################################################################################### array create test

In [40]:
# array 생성
array_test = np.arange(20)
array_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [65]:
# list 생성
list_test = list(range(0,20))
test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [66]:
# list를 array형태로 변경
np.array(list_test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
##################################################################################################### array reshape test

In [47]:
# reshape 예제 1
array_test.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [48]:
# reshape 예제 2
array_test.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [107]:
## reshape 예제 3
# 2차원 array 생성
array_test_2d = array_test.reshape(2,5,2)
print("2차원:\n")
print(array_test_2d)

print("\n")

# 2차원 array형태의 데이터를 1차원으로 다시 변경
print("1차원으로 변경:\n")
print(array_test_2d.ravel())

2차원:

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


1차원으로 변경:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
##################################################################################################### array shape check
'''
Data Check:

ndarray.shape : 배열의 각 축(axis)의 크기
ndarray.ndim : 축의 개수(Dimension)
ndarray.dtype : 각 요소(Element)의 타입
ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
ndarray.size : 전체 요소(Element)의 개수
'''

In [58]:
# shape 확인 예제 1
print("shape:", array_test.reshape(2,2,5).shape)
print("ndim:", array_test.reshape(2,2,5).ndim)
print("dtype:", array_test.reshape(2,2,5).dtype)
print("itemsize:", array_test.reshape(2,2,5).itemsize)
print("size:", array_test.reshape(2,2,5).size)

shape: (2, 2, 5)
ndim: 3
dtype: int32
itemsize: 4
size: 20


In [59]:
# shape 확인 예제 2
print("shape:", array_test.reshape(2,5,2).shape)
print("ndim:", array_test.reshape(2,5,2).ndim)
print("dtype:", array_test.reshape(2,5,2).dtype)
print("itemsize:", array_test.reshape(2,5,2).itemsize)
print("size:", array_test.reshape(2,5,2).size)

shape: (2, 5, 2)
ndim: 3
dtype: int32
itemsize: 4
size: 20


In [ ]:
##################################################################################################### Basic Calculation

In [118]:
# 연산 예제 - 1차원 (1)

# a_array 생성
a = np.arange(4)
print("a_array:", a)

# b_array 생성
b = np.arange(4,8)
print("b_array:", b)

# a + b 연산
print("a+b_array:", a+b)

a_array: [0 1 2 3]
b_array: [4 5 6 7]
a+b_array: [ 4  6  8 10]


In [84]:
## 연산 예제 - 1차원 (2)

# data 생성
test_calc_1d = np.arange(10)

# 연산
print("original_1d:", test_calc_1d)
print("original_1d +1:", test_calc_1d + 1)
print("original_1d *2:", test_calc_1d * 2)
print("original_1d **2:", test_calc_1d**2)

original_1d: [0 1 2 3 4 5 6 7 8 9]
original_1d +1: [ 1  2  3  4  5  6  7  8  9 10]
original_1d *2: [ 0  2  4  6  8 10 12 14 16 18]
original_1d **2: [ 0  1  4  9 16 25 36 49 64 81]


In [92]:
## 연산 예제 - 2차원

# data 생성
test_calc_2d = np.arange(8).reshape(2,1,4)

# 연산
print("Original_2d:\n", test_calc_2d)
print("\n")
print("Original_2d +1:\n", test_calc_2d + 1)
print("\n")
print("Original_2d *2:\n", test_calc_2d * 2)
print("\n")
print("Original_2d **2:\n", test_calc_2d**2)

Original_2d:
 [[[0 1 2 3]]

 [[4 5 6 7]]]


Original_2d +1:
 [[[1 2 3 4]]

 [[5 6 7 8]]]


Original_2d *2:
 [[[ 0  2  4  6]]

 [[ 8 10 12 14]]]


Original_2d **2:
 [[[ 0  1  4  9]]

 [[16 25 36 49]]]


In [136]:
## min, max, mean, median, & quantile 연산

# array 생성
stat_test = np.arange(5,10)

# 연산 
print("Array:", stat_test)
print("min:", np.min(stat_test))
print("max:", np.max(stat_test))
print("mean:", np.mean(stat_test))
print("median:", np.median(stat_test))
print("quantile 25%:", np.quantile(stat_test, 0.25)) # (0, 0.25, 0.5, 0.75, 1.0)

Array: [5 6 7 8 9]
min: 5
max: 9
mean: 7.0
median: 7.0
quantile 25%: 6.0
