In [2]:
# chap2
# 실습 : 2차원 배열 데이터 입출력 
import numpy


In [14]:
# numpy 배열
# numpy 에서 배열은 동일한 타입의 값들을 가지며, 배열의 차원을 rank라 하고
# 각 차원의 크기를 튜플로 표시하는 것을 shape라고 한다. 

# 1. Numpy 1차원 배열 생성 및 Append 예제

arr_1d = numpy.array([1,2,3,4])

# 배열에 요소를 추가하는 방법
arr1 = numpy.array([])
arr1 = numpy.append(arr1, numpy.array([1,2,3]))
arr1 = numpy.append(arr1, numpy.array([4,5]))

print("'1D Array'")
print(arr_1d)
print("\n'1D Append Array'")
print(arr1)

# 2. 2차원 배열 생성 및 append 예제

arr_2d = numpy.array([[1,2,3],[4,5,6]])
print("\n'2D Array'")
print(arr_2d)

# 2차원 배열에 요소를 추가하는 방법
# 배열을 numpy.empty를 사용하여 초기화
arr2 = numpy.empty((0,3), int)

# 배열을 추가
# 추가하는 배열의 요소수는 초기화 했던 길이와 동일해야한다.
# axis = 0 은 행으로 추가한다는 의미
arr2 = numpy.append(arr2, numpy.array([[1,2,3]]), axis=0)
arr2 = numpy.append(arr2, numpy.array([[4,5,6]]), axis=0)

print("\n'2D Array Append'")
print(arr2)



'1D Array'
[1 2 3 4]

'1D Append Array'
[1. 2. 3. 4. 5.]

'2D Array'
[[1 2 3]
 [4 5 6]]

'2D Array Append'
[[1 2 3]
 [4 5 6]]


In [23]:
# 2차원 배열 슬라이스
arr = numpy.empty((0,3), int)
arr = numpy.append(arr, numpy.array([[1, 2, 3]]), axis = 0)
arr = numpy.append(arr, numpy.array([[4,5,6]]), axis = 0)

print(arr)

print("\n'Array Indexing'")

print(arr[0,1])
print(arr[1, :2])
print(arr[:, 1])

[[1 2 3]
 [4 5 6]]

'Array Indexing'
2
[4 5]
[2 5]
