In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #
#                                              실전 데이터 분석 코드 (교재 초보자 용)                                                    #
#                                                                                                                                     #
#                                                                                                             "Handmade by JHL"       #
#######################################################################################################################################

In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #                                    
#                                                     판다스 - 데이터 핸들링 기초                                                       #
#                                                                                                                                     #
#                                                                                                                                     #
#######################################################################################################################################

In [7]:
# 필요 라이브러리 불러오기
import pandas 
import numpy 
import warnings 

warnings.filterwarnings(action="ignore")
# 데이터 경로
PATH = "C:/Users/WAI/OneDrive/03.WORKSPACE/00.DATA/99.KAGGLE/insurance/"
# 데이터 명
DATA_NAME = "14. Learning from Imbalaced Insurance Data/aug_train_mod_2.csv"

In [9]:
# 데이터 불러오기 및 데이터 규모 파악
df = pandas.read_csv(PATH + DATA_NAME, index_col =False)
print("Data Shape:", df.shape)

# 데이터 앞 5개 확인
print(df.head())

Data Shape: (177355, 14)
       id  Gender   Age  Driving_License  Region_Code  Previously_Insured  \
0   17163       0  42.0              1.0         28.0                   0   
1   32023       1  66.0              1.0         33.0                   0   
2   71711       0  51.0              1.0          8.0                   0   
3  331781       0  38.0              1.0         28.0                   1   
4  290704       1  45.0              1.0         28.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes    32901.909565                  26.0    135.0   
1    1-2 Year            Yes    35841.000000                 124.0    253.0   
2    1-2 Year            Yes     2630.000000                  26.0    209.0   
3    1-2 Year             No     2630.000000                  26.0     51.0   
4    1-2 Year            Yes    32901.909565                 124.0    262.0   

   Response  birth_date insure_date  

In [10]:
# 데이터 마지막 5개 확인
df.tail()

id  Gender        Age  Driving_License  Region_Code  \
177350  447797       0  38.535247              1.0         28.0   
177351  157507       0  56.000000              1.0         17.0   
177352  498091       1  48.000000              1.0         28.0   
177353   89317       0  47.000000              1.0         43.0   
177354  165293       0  45.000000              1.0         28.0   

        Previously_Insured Vehicle_Age Vehicle_Damage  Annual_Premium  \
177350                   0    1-2 Year            Yes    37138.000000   
177351                   0    1-2 Year            Yes    32901.909565   
177352                   0    1-2 Year            Yes    32901.909565   
177353                   0    1-2 Year            Yes    32774.000000   
177354                   0    1-2 Year            Yes    40443.000000   

        Policy_Sales_Channel  Vintage  Response  birth_date insure_date  
177350                  26.0    276.0         1    19901205  1990-01-22  
177351                 124.0    244.0         0    20010701  2006-08-08  
177352                  26.0     80.0         1    19910714  1993-09-07  
177353                 124.0    105.0         0    19960620  2004-05-28  
177354                  26.0    187.0         0    19950825  1997-09-04

In [11]:
# 데이터 정보 파악 1
df.describe()

id         Gender            Age  Driving_License  \
count  177355.000000  177355.000000  177355.000000    177355.000000   
mean   233602.343272       0.380373      48.378963         0.996307   
std    139001.376802       0.485480      12.430505         0.060659   
min         1.000000       0.000000      20.000000         0.000000   
25%    114619.500000       0.000000      39.000000         1.000000   
50%    229690.000000       0.000000      46.000000         1.000000   
75%    344014.000000       1.000000      56.000000         1.000000   
max    508145.000000       1.000000      85.000000         1.000000   

         Region_Code  Previously_Insured  Annual_Premium  \
count  177355.000000       177355.000000   177355.000000   
mean       27.029590            0.317082    27857.988969   
std        12.111199            0.465341    11781.405474   
min         0.000000            0.000000     2630.000000   
25%        23.000000            0.000000    26294.000000   
50%        28.000000            0.000000    32901.909565   
75%        31.000000            1.000000    34021.000000   
max        52.000000            1.000000    42359.000000   

       Policy_Sales_Channel        Vintage       Response    birth_date  
count         177355.000000  177355.000000  177355.000000  1.773550e+05  
mean              70.230673     144.259045       0.255933  1.999569e+07  
std               49.248534      77.842845       0.436386  5.769066e+04  
min                1.000000      10.000000       0.000000  1.990010e+07  
25%               26.000000      77.000000       0.000000  1.995010e+07  
50%               26.000000     144.000000       0.000000  1.999123e+07  
75%              124.000000     212.000000       1.000000  2.005011e+07  
max              137.000000     279.000000       1.000000  2.010010e+07

In [12]:
# 데이터 정보 파악 2
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 177355 entries, 0 to 177354
Data columns (total 14 columns):
 #   Column                Non-Null Count   Dtype  
---  ------                --------------   -----  
 0   id                    177355 non-null  int64  
 1   Gender                177355 non-null  int64  
 2   Age                   177355 non-null  float64
 3   Driving_License       177355 non-null  float64
 4   Region_Code           177355 non-null  float64
 5   Previously_Insured    177355 non-null  int64  
 6   Vehicle_Age           177355 non-null  object 
 7   Vehicle_Damage        177355 non-null  object 
 8   Annual_Premium        177355 non-null  float64
 9   Policy_Sales_Channel  177355 non-null  float64
 10  Vintage               177355 non-null  float64
 11  Response              177355 non-null  int64  
 12  birth_date            177355 non-null  int64  
 13  insure_date           177355 non-null  object 
dtypes: float64(6), int64(5), object(3)
memory usage: 18.

In [13]:
# 결측치 파악
df.isnull().sum()

id                      0
Gender                  0
Age                     0
Driving_License         0
Region_Code             0
Previously_Insured      0
Vehicle_Age             0
Vehicle_Damage          0
Annual_Premium          0
Policy_Sales_Channel    0
Vintage                 0
Response                0
birth_date              0
insure_date             0
dtype: int64

In [16]:
# unique/nunique 한 값 확인
print("unique:", df["Response"].unique())
print("nunque:", df["Response"].nunique())

unique: [0 1]
nunque: 2


In [17]:
# 범주형 데이터 빈도수 파악
df["Response"].value_counts()

0    131964
1     45391
Name: Response, dtype: int64

In [18]:
# target컬럼 데이터만 추출
df[["Response"]].head()

Response
0         0
1         0
2         0
3         0
4         0

In [19]:
# ID 및 target 컬럼 데이터만 추출
df[["Response", "id"]].head()

Response      id
0         0   17163
1         0   32023
2         0   71711
3         0  331781
4         0  290704

In [21]:
# 특정 컬럼 통계치 확인
df["Vintage"].describe()

count    177355.000000
mean        144.259045
std          77.842845
min          10.000000
25%          77.000000
50%         144.000000
75%         212.000000
max         279.000000
Name: Vintage, dtype: float64

In [22]:
# 특정 타입의 데이터만 추출
# ("object, int32, int64, float32, float64" - 중 선택 가능)
df.select_dtypes("object")

Vehicle_Age Vehicle_Damage insure_date
0         1-2 Year            Yes  1996-08-16
1         1-2 Year            Yes  2001-07-04
2         1-2 Year            Yes  2000-06-18
3         1-2 Year             No  1992-04-06
4         1-2 Year            Yes  2001-05-15
...            ...            ...         ...
177350    1-2 Year            Yes  1990-01-22
177351    1-2 Year            Yes  2006-08-08
177352    1-2 Year            Yes  1993-09-07
177353    1-2 Year            Yes  2004-05-28
177354    1-2 Year            Yes  1997-09-04

[177355 rows x 3 columns]

In [23]:
### 수치형 데이터 인덱싱 - 기본

# index 위치로 조회
df.loc[:5]

# column 위치로 조회
df.loc[:5,"Vintage"]

# target에서 0을 만족하는 데이터만 추출
df[ df.loc[:, "Response"] == 0 ]

# target 이 0을 갖고 나이가 20대이상인
df[ (df["Response"] == 0) & (df["Age"] >= 20) ]

id  Gender   Age  Driving_License  Region_Code  \
0        17163       0  42.0              1.0         28.0   
1        32023       1  66.0              1.0         33.0   
2        71711       0  51.0              1.0          8.0   
3       331781       0  38.0              1.0         28.0   
4       290704       1  45.0              1.0         28.0   
...        ...     ...   ...              ...          ...   
177347  366734       0  46.0              1.0          3.0   
177348  472055       1  53.0              1.0         48.0   
177351  157507       0  56.0              1.0         17.0   
177353   89317       0  47.0              1.0         43.0   
177354  165293       0  45.0              1.0         28.0   

        Previously_Insured Vehicle_Age Vehicle_Damage  Annual_Premium  \
0                        0    1-2 Year            Yes    32901.909565   
1                        0    1-2 Year            Yes    35841.000000   
2                        0    1-2 Year            Yes     2630.000000   
3                        1    1-2 Year             No     2630.000000   
4                        0    1-2 Year            Yes    32901.909565   
...                    ...         ...            ...             ...   
177347                   0    1-2 Year            Yes    21504.000000   
177348                   1    1-2 Year             No     2630.000000   
177351                   0    1-2 Year            Yes    32901.909565   
177353                   0    1-2 Year            Yes    32774.000000   
177354                   0    1-2 Year            Yes    40443.000000   

        Policy_Sales_Channel  Vintage  Response  birth_date insure_date  
0                       26.0    135.0         0    20080411  1996-08-16  
1                      124.0    253.0         0    20040818  2001-07-04  
2                       26.0    209.0         0    20031110  2000-06-18  
3                       26.0     51.0         0    20061204  1992-04-06  
4                      124.0    262.0         0    19960115  2001-05-15  
...                      ...      ...       ...         ...         ...  
177347                  26.0    105.0         0    19980101  2008-12-16  
177348                  26.0    122.0         0    20001018  1991-12-22  
177351                 124.0    244.0         0    20010701  2006-08-08  
177353                 124.0    105.0         0    19960620  2004-05-28  
177354                  26.0    187.0         0    19950825  1997-09-04  

[131964 rows x 14 columns]

In [24]:
# 컬럼명 변경
df.rename(columns={"id": "ID_num" }, inplace=True)
df.head()

ID_num  Gender   Age  Driving_License  Region_Code  Previously_Insured  \
0   17163       0  42.0              1.0         28.0                   0   
1   32023       1  66.0              1.0         33.0                   0   
2   71711       0  51.0              1.0          8.0                   0   
3  331781       0  38.0              1.0         28.0                   1   
4  290704       1  45.0              1.0         28.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes    32901.909565                  26.0    135.0   
1    1-2 Year            Yes    35841.000000                 124.0    253.0   
2    1-2 Year            Yes     2630.000000                  26.0    209.0   
3    1-2 Year             No     2630.000000                  26.0     51.0   
4    1-2 Year            Yes    32901.909565                 124.0    262.0   

   Response  birth_date insure_date  
0         0    20080411  1996-08-16  
1         0    20040818  2001-07-04  
2         0    20031110  2000-06-18  
3         0    20061204  1992-04-06  
4         0    19960115  2001-05-15

In [25]:
# 새로운 컬럼 추가
df["new_col"] = 0
df.head()

ID_num  Gender   Age  Driving_License  Region_Code  Previously_Insured  \
0   17163       0  42.0              1.0         28.0                   0   
1   32023       1  66.0              1.0         33.0                   0   
2   71711       0  51.0              1.0          8.0                   0   
3  331781       0  38.0              1.0         28.0                   1   
4  290704       1  45.0              1.0         28.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes    32901.909565                  26.0    135.0   
1    1-2 Year            Yes    35841.000000                 124.0    253.0   
2    1-2 Year            Yes     2630.000000                  26.0    209.0   
3    1-2 Year             No     2630.000000                  26.0     51.0   
4    1-2 Year            Yes    32901.909565                 124.0    262.0   

   Response  birth_date insure_date  new_col  
0         0    20080411  1996-08-16        0  
1         0    20040818  2001-07-04        0  
2         0    20031110  2000-06-18        0  
3         0    20061204  1992-04-06        0  
4         0    19960115  2001-05-15        0

In [26]:
# 컬럼 삭제
df.drop("new_col", axis=1, inplace=True)
df.head()

ID_num  Gender   Age  Driving_License  Region_Code  Previously_Insured  \
0   17163       0  42.0              1.0         28.0                   0   
1   32023       1  66.0              1.0         33.0                   0   
2   71711       0  51.0              1.0          8.0                   0   
3  331781       0  38.0              1.0         28.0                   1   
4  290704       1  45.0              1.0         28.0                   0   

  Vehicle_Age Vehicle_Damage  Annual_Premium  Policy_Sales_Channel  Vintage  \
0    1-2 Year            Yes    32901.909565                  26.0    135.0   
1    1-2 Year            Yes    35841.000000                 124.0    253.0   
2    1-2 Year            Yes     2630.000000                  26.0    209.0   
3    1-2 Year             No     2630.000000                  26.0     51.0   
4    1-2 Year            Yes    32901.909565                 124.0    262.0   

   Response  birth_date insure_date  
0         0    20080411  1996-08-16  
1         0    20040818  2001-07-04  
2         0    20031110  2000-06-18  
3         0    20061204  1992-04-06  
4         0    19960115  2001-05-15

In [28]:
# 컬럼에 들어있는 특정 데이터 replace
# "0" --> "D" 변경
df.loc[df["Previously_Insured"] == 0, "Previously_Insured_2"]  = "D"
df["Previously_Insured_2"].value_counts()

D    121119
Name: Previously_Insured_2, dtype: int64

In [ ]:
# 작업 완료된 데이터프레임 컴퓨터에 파일(csv) 형태로 저장
df.to_csv("원하는 파일명을 쓰시오.csv")

In [ ]:
#######################################################################################################################################
#                                                                                                                                     #
#                                                                                                                                     #                                    
#                                                       넘파이 - 데이터 연산 기초                                                       #
#                                                                                                                                     #
#                                                                                                                                     #
#######################################################################################################################################

In [3]:
# 필요 라이브러리 불러오기
import pandas
import numpy

In [ ]:
'''

넘파이(Numpy)는 Python에서 벡터, 행렬(matrix) 등 수치 연산을 수행하는 라이브러리입니다.           
내부적으로 C언어로 구현되어 있어 빠른 연산 속도를 자랑합니다.

넘파이에서는 모든 배열의 값이 기본적으로 같은 타입이어야 합니다.
그리고 넘파이에서는 각 차원(Dimension)을 축(axis)라고 표현합니다.

3D Space의 포인트를 [1,2,1] 과 같은 배열(array)로 표현가능 한데, 1개의 축을 가진다고 표현합니다.
(여기서 축은 3개의 요소(Element)를 가지고 있다고 하며 길이(Length)도 3입니다.)

넘파이에서 배열은 ndarray 또는 array라고도 부릅니다. 



Vector are implemented as dynamic arrays with list interface 
whereas arrays can be implemented as statically or dynamically with primitive data type interface. 
Size of arrays are fixed whereas the vectors are resizable 
i.e they can grow and shrink as vectors are allocated on heap memory.

'''

In [ ]:
##################################################################################################### array create test

In [33]:
# array 생성
array_test = numpy.arange(20)
array_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
# list 생성
list_test = list(range(0,20))
list_test

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [36]:
# list를 array형태로 변경
numpy.array(list_test)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
##################################################################################################### array reshape test

In [37]:
# reshape 예제 1
array_test.reshape(2,2,5)

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]]])

In [38]:
# reshape 예제 2
array_test.reshape(2,5,2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [39]:
## reshape 예제 3
# 2차원 array 생성
array_test_2d = array_test.reshape(2,5,2)
print("2차원:\n")
print(array_test_2d)

print("\n")

# 2차원 array형태의 데이터를 1차원으로 다시 변경
print("1차원으로 변경:\n")
print(array_test_2d.ravel())

2차원:

[[[ 0  1]
  [ 2  3]
  [ 4  5]
  [ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]
  [14 15]
  [16 17]
  [18 19]]]


1차원으로 변경:

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
##################################################################################################### array shape check
'''
Data Check:

ndarray.shape : 배열의 각 축(axis)의 크기
ndarray.ndim : 축의 개수(Dimension)
ndarray.dtype : 각 요소(Element)의 타입
ndarray.itemsize : 각 요소(Element)의 타입의 bytes 크기
ndarray.size : 전체 요소(Element)의 개수
'''

In [40]:
# shape 확인 예제 1
print("shape:", array_test.reshape(2,2,5).shape)
print("ndim:", array_test.reshape(2,2,5).ndim)
print("dtype:", array_test.reshape(2,2,5).dtype)
print("itemsize:", array_test.reshape(2,2,5).itemsize)
print("size:", array_test.reshape(2,2,5).size)

shape: (2, 2, 5)
ndim: 3
dtype: int32
itemsize: 4
size: 20


In [41]:
# shape 확인 예제 2
print("shape:", array_test.reshape(2,5,2).shape)
print("ndim:", array_test.reshape(2,5,2).ndim)
print("dtype:", array_test.reshape(2,5,2).dtype)
print("itemsize:", array_test.reshape(2,5,2).itemsize)
print("size:", array_test.reshape(2,5,2).size)

shape: (2, 5, 2)
ndim: 3
dtype: int32
itemsize: 4
size: 20


In [ ]:
##################################################################################################### Basic Calculation

In [42]:
# 연산 예제 - 1차원 (1)

# a_array 생성
a = numpy.arange(4)
print("a_array:", a)

# b_array 생성
b = numpy.arange(4,8)
print("b_array:", b)

# a + b 연산
print("a+b_array:", a+b)

a_array: [0 1 2 3]
b_array: [4 5 6 7]
a+b_array: [ 4  6  8 10]


In [43]:
## 연산 예제 - 1차원 (2)

# data 생성
test_calc_1d = numpy.arange(10)

# 연산
print("original_1d:", test_calc_1d)
print("original_1d +1:", test_calc_1d + 1)
print("original_1d *2:", test_calc_1d * 2)
print("original_1d **2:", test_calc_1d**2)

original_1d: [0 1 2 3 4 5 6 7 8 9]
original_1d +1: [ 1  2  3  4  5  6  7  8  9 10]
original_1d *2: [ 0  2  4  6  8 10 12 14 16 18]
original_1d **2: [ 0  1  4  9 16 25 36 49 64 81]


In [44]:
## 연산 예제 - 2차원

# data 생성
test_calc_2d = numpy.arange(8).reshape(2,1,4)

# 연산
print("Original_2d:\n", test_calc_2d)
print("\n")
print("Original_2d +1:\n", test_calc_2d + 1)
print("\n")
print("Original_2d *2:\n", test_calc_2d * 2)
print("\n")
print("Original_2d **2:\n", test_calc_2d**2)

Original_2d:
 [[[0 1 2 3]]

 [[4 5 6 7]]]


Original_2d +1:
 [[[1 2 3 4]]

 [[5 6 7 8]]]


Original_2d *2:
 [[[ 0  2  4  6]]

 [[ 8 10 12 14]]]


Original_2d **2:
 [[[ 0  1  4  9]]

 [[16 25 36 49]]]


In [46]:
## min, max, mean, median, & quantile 연산

# array 생성
stat_test = numpy.arange(5,10)

# 연산 
print("Array:", stat_test)
print("min:", numpy.min(stat_test))
print("max:", numpy.max(stat_test))
print("mean:", numpy.mean(stat_test))
print("median:", numpy.median(stat_test))
print("quantile 25%:", numpy.quantile(stat_test, 0.25)) # (0, 0.25, 0.5, 0.75, 1.0)

Array: [5 6 7 8 9]
min: 5
max: 9
mean: 7.0
median: 7.0
quantile 25%: 6.0
